defaults: &defaults
  main:
    diurna_baza: ''
    activities: ''
    vat_rate: ''
    currencies: ''
    paid_by: ''
    salar_baza: ''
  company:
    name: ''
    registration: ''
    vat: ''
    address: ''
    acc_ron: ''
    acc_eur: ''
    bank: ''
    capital: ''
    phone: ''
    email: ''
    contact: ''
  util:
    use_s3: 'false'
    s3_bucket: ''
    s3_access_key_id: ''
    s3_secret_access_key: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults