defaults: &defaults
  main:
    diurna_zi: ''
    activities: ''
    vat_rate: ''
    currencies: ''
    paid_by: ''
    salar_baza: ''
  company:
    name: ''
    registration: ''
    vat: ''
    address: ''
    acc_ron: ''
    acc_eur: ''
    bank: ''
    capital: ''
    phone: ''
    email: ''
    contact: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
